### ISSUE TITLE
E not working for unlocking/locking

### ISSUE THREAD

**Issue by Dejvi1** [guillerp8/guille_doorlock#3]
Hello after some time some players cannot open doors even tho they have bind for E
Command for unlocking works so if you could help me please ?

**Comment by guillerp8** [comment]
The command is default binded using a keymap in the key E, check if the keymap is correctly set or change the default key

**Comment by Dejvi1** [comment]
i did not touched the key binds at all thats the thing even if i try to replace script for newly downloaded it does the same thing..
Maybe do you have any version with IsControlJustPressed instead of keybind option ?
